### ISSUE TITLE
Unable to assign value by condition using Update

### ISSUE THREAD

**Issue by vsurajevs** [loresoft/EntityFramework.Extended#147]
I am trying to write linq expression that updates all my records and sets their Default field based on id match condition:

`
m_context.Languages.Update(x => 
                new Language {Default = x.LanguageId == _languageId ? true : false}
            );
`
But in that case I am getting an error:

`System.Data.SqlClient.SqlException: Ambiguous column name 'LanguageId'.
at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
at EntityFramework.Batch.SqlServerBatchRunner.<InternalUpdate>d__15`1.MoveNext()
--- End of inner exception stack trace ---
at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
at EntityFramework.Extensions.BatchExtensions.Update[TEntity](IQueryable`1 source, Expression`1 updateExpression)`
What I am going wrong or it is just a bug? I tried other conditions and it seems it works fine until another field participates in condition:

` context.Languages.Update(x => new Language {Default = !x.Default}); //fine
 context.Languages.Update(x => new Language {Default = true == true}); //fine
 context.Languages.Update(x => new Language {Version = x.Version + 1}); //fine
 context.Languages.Update(x => new Language {Default = x.LanguageId == langId}); //error`

**Comment by GFoley83** [comment]
+1
