### ISSUE TITLE
An item with the same key has already been added

### ISSUE THREAD

**Issue by StasPerekrestov** [loresoft/EntityFramework.Extended#149]
It's hard to reproduce because it happens really seldom.
```
public async Task DeleteItems(Guid id) {
		//.......
			await Context.Items.Where(i => i.Id == id).DeleteAsync();
			await Context.SaveChangesAsync();
		}
```

```
Stack Trace
System.ArgumentException: An item with the same key has already been added.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Dynamic.ClassFactory.GetDynamicClass(IEnumerable`1 properties)
   at System.Linq.Dynamic.ExpressionParser.ParseNew()
   at System.Linq.Dynamic.ExpressionParser.ParseIdentifier()
   at System.Linq.Dynamic.ExpressionParser.ParsePrimary()
   at System.Linq.Dynamic.ExpressionParser.ParseUnary()
   at System.Linq.Dynamic.ExpressionParser.ParseMultiplicative()
   at System.Linq.Dynamic.ExpressionParser.ParseAdditive()
   at System.Linq.Dynamic.ExpressionParser.ParseComparison()
   at System.Linq.Dynamic.ExpressionParser.ParseLogicalAnd()
   at System.Linq.Dynamic.ExpressionParser.ParseLogicalOr()
   at System.Linq.Dynamic.ExpressionParser.ParseExpression()
   at System.Linq.Dynamic.ExpressionParser.Parse(Type resultType)
   at System.Linq.Dynamic.DynamicQueryable.Select(IQueryable source, String selector, Object[] values)
   at EntityFramework.Batch.SqlServerBatchRunner.GetSelectSql[TEntity](ObjectQuery`1 query, EntityMap entityMap, DbCommand command)
   at EntityFramework.Batch.SqlServerBatchRunner.<InternalDelete>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
```

**Comment by m-rakic** [comment]
We get same error but on getting the data only when we first time start the application, after first run is done everything is fine. we are using dynamic linq library but is crashing in same point like. Seams on start something is not checked correctly. 

Hope helps.

   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Dynamic.ClassFactory.GetDynamicClass(IEnumerable`1 properties)
   at System.Linq.Dynamic.DynamicExpression.CreateClass(IEnumerable`1 properties)
   at System.Linq.Dynamic.ExpressionParser.ParseNew()
   at System.Linq.Dynamic.ExpressionParser.ParseIdentifier()
   at System.Linq.Dynamic.ExpressionParser.ParsePrimaryStart()
   at System.Linq.Dynamic.ExpressionParser.ParsePrimary()
   at System.Linq.Dynamic.ExpressionParser.ParseUnary()
   at System.Linq.Dynamic.ExpressionParser.ParseMultiplicative()
   at System.Linq.Dynamic.ExpressionParser.ParseAdditive()
   at System.Linq.Dynamic.ExpressionParser.ParseComparison()
   at System.Linq.Dynamic.ExpressionParser.ParseLogicalAnd()
   at System.Linq.Dynamic.ExpressionParser.ParseLogicalOr()
   at System.Linq.Dynamic.ExpressionParser.ParseExpression()
   at System.Linq.Dynamic.ExpressionParser.Parse(Type resultType)
   at System.Linq.Dynamic.DynamicExpression.ParseLambda(ParameterExpression[] parameters, Type resultType, String expression, Object[] values)
   at System.Linq.Dynamic.DynamicExpression.ParseLambda(Type itType, Type resultType, String expression, Object[] values)
   at System.Linq.Dynamic.DynamicQueryable.GroupBy(IQueryable source, String keySelector, String elementSelector, Object[] values)
