### ISSUE TITLE
Update with condition in form x => {EmptyArray}.Contains(x.SomeValue) fails

### ISSUE THREAD

**Issue by vsurajevs** [loresoft/EntityFramework.Extended#169]
`myService.Update(
                x => response.SomeIds.Contains(x.MasterId),
                x => new ChildCampaign {SyncStatusChanged = false}
            );`

In case if `response.SomeIds` is empty fails with:

*Failed to process the job 'System.AggregateException: One or more errors occurred. ---> System.Data.SqlClient.SqlException: Invalid column name 'Id'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at EntityFramework.Batch.SqlServerBatchRunner.<InternalUpdate>d__15`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at EntityFramework.Batch.SqlServerBatchRunner.Update[TEntity](ObjectContext objectContext, EntityMap entityMap, ObjectQuery`1 query, Expression`1 updateExpression)
   at EntityFramework.Extensions.BatchExtensions.Update[TEntity](IQueryable`1 source, Expression`1 updateExpression)*

SQL generated:

`exec sp_executesql N'UPDATE [dbo].[ChildCampaigns] SET 
[SyncStatusChanged] = @p__update__0 
FROM [dbo].[ChildCampaigns] AS j0 INNER JOIN (
SELECT 
    1 AS [C1], 
    CAST(NULL AS int) AS [C2]
    FROM  ( SELECT 1 AS X ) AS [SingleRowTable1]
    WHERE 1 = 0
) AS j1 ON (j0.[Id] = j1.[Id])',N'@p__update__0 bit',@p__update__0=0`

**Comment by emumanu** [comment]
+1

I have just hit this bug too

**Comment by antonberezan** [comment]
+1
The same issue.

**Comment by homam1** [comment]
+1
Same issue

**Comment by neoGeneva** [comment]
+1

**Comment by vsurajevs** [comment]
I already forgot that I raised this one a while back.. 

Still having similar issue with batch extensions: 

`context.MyEntity.Where(x => emptyArray.Contains(x.SomeField)).Delete();`

**Comment by SylwesterZarebski** [comment]
It looks like it is the same bug as #94 .
