### ISSUE TITLE
TransactionScope and EF.Extended 5.0.0.73

### ISSUE THREAD

**Issue by felipeogarcia** [loresoft/EntityFramework.Extended#179]
I'm trying to use a simple Delete inside a TransactionScope and I'm receiving the following error:

    System.InvalidOperationException: Connection is already part of a local or a distributed transaction
       at Oracle.DataAccess.Client.OracleConnection.BeginTransaction(IsolationLevel isolationLevel)
       at Oracle.DataAccess.Client.OracleConnection.BeginDbTransaction(IsolationLevel isolationLevel)
       at EntityFramework.Batch.SqlServerBatchRunner.Delete[TEntity](ObjectContext objectContext, EntityMap entityMap, ObjectQuery`1 query)
       at EntityFramework.Extensions.BatchExtensions.Delete[TEntity](IQueryable`1 source)

My code is as follows:

	using (var scope = new TransactionScope(TransactionScopeOption.Required, new TransactionOptions { IsolationLevel = IsolationLevel.ReadCommitted }))
	{
		using (var context = new DataEntities())
		{
			context.Parts.Where(x => x.Number == number).Delete(); // code fails here
			context.SaveChanges();
		}
		
		scope.Complete();
	}

Is there any way that I can avoid colliding TransactionScope and EF.Extended?

**Comment by vvenegasv** [comment]
Hi, meaby could you try with context.Database.BeginTransaction() ?

**Comment by felipeogarcia** [comment]
@vvenegasv I wish I could. I'm using EF 5 and the method you mentioned is EF 6 onwards.
