### ISSUE TITLE
Future query failed with an exception

### ISSUE THREAD

**Issue by juanonsoftware** [loresoft/EntityFramework.Extended#180]
Hi,

I try to do some test with Future method as bellow

```
var projects1 = context.Projects.Future();
var employees1 = context.Employees.Future();
var l1 = projects1.ToList();
```

But it doesn't work and below is the exception I got. Could you please help ?

System.MethodAccessException was unhandled
  HResult=-2146233072
  Message=Attempt by method 'EntityFramework.Future.FutureRunner.CreateFutureCommand(System.Data.Entity.Core.Objects.ObjectContext, System.Collections.Generic.IEnumerable`1<EntityFramework.Future.IFutureQuery>)' to access method 'System.Data.Entity.Core.EntityClient.EntityConnection.get_CurrentTransaction()' failed.
  Source=EntityFramework.Extended
  StackTrace:
       at EntityFramework.Future.FutureRunner.CreateFutureCommand(ObjectContext context, IEnumerable`1 futureQueries)
       at EntityFramework.Future.FutureRunner.ExecuteFutureQueries(ObjectContext context, IList`1 futureQueries)
       at EntityFramework.Future.FutureContext.ExecuteFutureQueries()
       at EntityFramework.Future.FutureQueryBase`1.GetResult()
       at EntityFramework.Future.FutureQuery`1.GetEnumerator()
       at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
       at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
       at EF01.Program.Main(String[] args) in d:\Wip\Practices\OpenSource\70-487\EF01\Program.cs:line 28
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by juanonsoftware** [comment]
Bellow are version of libraries

  <package id="EntityFramework" version="6.1.0" targetFramework="net45" />
  <package id="EntityFramework.Extended" version="6.1.0.168" targetFramework="net45" />

**Comment by vvenegasv** [comment]
I think this project has no support by loresoft. I suggest you that clone repository on your desktop and debug by yourself this error.

I have no idea why you get this exception.

Good luck

**Comment by trecio** [comment]
I had exactly the same problem. For some reason update to EntityFramework 6.1.3 made it work.

**Comment by alexeysolonets** [comment]
@trecio thank you, upgrading to EntityFramework 6.1.3 helps!
