### ISSUE TITLE
This is a bug , Field of condition can not be used to update

### ISSUE THREAD

**Issue by carldai0106** [loresoft/EntityFramework.Extended#206]
If you use a filed to filter, but you can not the field to update. see below

```csharp
        [Fact]
        public void Batch_Tests()
        {
            using (var context = new BatchDbContext())
            {
                context.Customers.Where(x => x.Age < 30).Update(x => new Customer { Age = x.Age + 10});
            }
        }
```

at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at EntityFramework.Batch.SqlServerBatchRunner.Update[TEntity](ObjectContext objectContext, EntityMap entityMap, ObjectQuery`1 query, Expression`1 updateExpression)
   at EntityFramework.Extensions.BatchExtensions.Update[TEntity](IQueryable`1 source, Expression`1 updateExpression)
   at Bcs.Vhas.Tests.BatchTests.Batch_Tests() in D:\Work\Git\Github\bcsint\VhasTest\Bcs.Vhas.Tests\Bcs.Vhas.Tests\BatchTests.cs:line 27
----- Inner Stack Trace -----
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at EntityFramework.Batch.SqlServerBatchRunner.<InternalUpdate>d__15`1.MoveNext()
结果 的消息:	
System.AggregateException : One or more errors occurred.
---- System.Data.SqlClient.SqlException : Filed  'Age' ambiguous。

I think we should change here : Source code file : SqlServerBatchRunner.cs line is 331.
```csharp
value = value.Replace(alias + ".", "");
//to
 value = value.Replace(alias + ".", "j0.");
```

@pwelter34 : Is it right?

**Comment by jmvtrinidad** [comment]
hi @carldai0106,

It seems that there is no bug in generating query from update.
I try this test
```

        [TestMethod]
        public void UpdateUsingFieldCondition()
        {
            var db = new TrackerContext();
            int count = db.Users
                .Where(u => u.Age > 30)
                .Update(u => new User
                {
                    Age = u.Age + 30
                });

            Assert.IsTrue(count == 0);
        }

```
and the result query is

```
UPDATE [dbo].[User] SET 
[Age] = [Age] + 30  
FROM [dbo].[User] AS j0 INNER JOIN (
SELECT 
    [Extent1].[Id] AS [Id]
    FROM [dbo].[User] AS [Extent1]
    WHERE [Extent1].[Age] > 30
) AS j1 ON (j0.[Id] = j1.[Id])
```

**Comment by carldai0106** [comment]
@jmvtrinidad 
This is my result query :
```bash
UPDATE [dbo].[Customer] SET 
[Age] = [Age] + 10  
FROM [dbo].[Customer] AS j0 INNER JOIN (
SELECT 
    [Extent1].[Age] AS [Age], 
    [Extent1].[Id] AS [Id]
    FROM [dbo].[Customer] AS [Extent1]
    WHERE [Extent1].[Age] < 30
) AS j1 ON (j0.[Id] = j1.[Id])
```

```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="EntityFramework" version="6.1.3" targetFramework="net452" />
  <package id="EntityFramework.Extended" version="6.1.0.168" targetFramework="net452" />
</packages>
```
My SQLServer : SqlServer 2014

**Comment by jmvtrinidad** [comment]
Just remove  `[Extent1].[Age]` to your linq method by selecting only the Id and `.Where(x => true)`.

**Comment by carldai0106** [comment]
I still think this is a bug. becuase my linq is not wrong.

**Comment by tonedev** [comment]
Just a note on reproducing the issue. It looks to only occur when the field you're filtering/updating is a key field (e.g. the primary key, or part of a composite primary key). carldai0106's suggested code change does look to resolve the issue.

**Comment by wangengzheng** [comment]
line 1           var data = context.EF6Test.Where(a => a.Name.Contains("good")).ToList();

    line 2            var count1 = context.EF6Test.Where(a => a.Name.Contains("good")).Update(a => new EF6Test() { Name = "no" });


     line 3           var count2= context.EF6Test.Where(x => x.Id < 10 && x.Id>=4).Update(x=>new EF6Test(){Name="good"});

data.count is 6

but count1 is 0 so i do update no work  in line 2

but count2 result is have results and can update

**Comment by wangengzheng** [comment]
line 1           var data = context.EF6Test.Where(a => a.Name.Contains("good")).ToList();

    line 2            var count1 = context.EF6Test.Where(a => a.Name.Contains("good")).Update(a => new EF6Test() { Name = "no" });


     line 3           var count2= context.EF6Test.Where(x => x.Id < 10 && x.Id>=4).Update(x=>new EF6Test(){Name="good"});

data.count is 6

but count1 is 0 so i do update no work  in line 2

but count2 result is have results and can update
